export type Sekki = {
  season: string;
  sekki: string;
  sekki_yomi: string;
  month: string;
  day: string;
  ko: string;
  ko_yomi: string;
};

const _sekkis: Sekki[] = [
  {
    season: "春",
    sekki: "立春",
    sekki_yomi: "りっしゅん",
    month: "2",
    day: "4",
    ko: "東風凍を解く",
    ko_yomi: "はるかぜ こおりをとく",
  },
  {
    season: "春",
    sekki: "立春",
    sekki_yomi: "りっしゅん",
    month: "2",
    day: "9",
    ko: "うぐいす鳴く",
    ko_yomi: "うぐいす なく",
  },
  {
    season: "春",
    sekki: "立春",
    sekki_yomi: "りっしゅん",
    month: "2",
    day: "14",
    ko: "魚氷を上る",
    ko_yomi: "うお こおりをいずる",
  },
  {
    season: "春",
    sekki: "雨水",
    sekki_yomi: "うすい",
    month: "2",
    day: "19",
    ko: "土脉潤い起こる",
    ko_yomi: "つちのしょう うるおいおこる",
  },
  {
    season: "春",
    sekki: "雨水",
    sekki_yomi: "うすい",
    month: "2",
    day: "24",
    ko: "霞始めてたなびく",
    ko_yomi: "かすみはじめてたなびく",
  },
  {
    season: "春",
    sekki: "雨水",
    sekki_yomi: "うすい",
    month: "3",
    day: "29",
    ko: "草木萌え動る",
    ko_yomi: "そうもく めばえいずる",
  },
  {
    season: "春",
    sekki: "啓蟄",
    sekki_yomi: "けいちつ",
    month: "3",
    day: "5",
    ko: "すごもりの虫戸を開く",
    ko_yomi: "すごもりむし とをひらく",
  },
  {
    season: "春",
    sekki: "啓蟄",
    sekki_yomi: "けいちつ",
    month: "3",
    day: "10",
    ko: "桃始めてさく",
    ko_yomi: "もも はじめてさく",
  },
  {
    season: "春",
    sekki: "啓蟄",
    sekki_yomi: "けいちつ",
    month: "3",
    day: "15",
    ko: "菜虫蝶となる",
    ko_yomi: "なむし ちょうとなる",
  },
  {
    season: "春",
    sekki: "春分",
    sekki_yomi: "しゅんぶん",
    month: "3",
    day: "20",
    ko: "雀始めて巣くう",
    ko_yomi: "すずめ はじめてすくう",
  },
  {
    season: "春",
    sekki: "春分",
    sekki_yomi: "しゅんぶん",
    month: "3",
    day: "25",
    ko: "桜始めて開く",
    ko_yomi: "さくら はじめてひらく",
  },
  {
    season: "春",
    sekki: "春分",
    sekki_yomi: "しゅんぶん",
    month: "3",
    day: "30",
    ko: "雷乃ち声を発す",
    ko_yomi: "かみなりすなわち こえをはっす",
  },
  {
    season: "春",
    sekki: "清明",
    sekki_yomi: "せいめい",
    month: "4",
    day: "4",
    ko: "玄鳥至る",
    ko_yomi: "つばめ いたる",
  },
  {
    season: "春",
    sekki: "清明",
    sekki_yomi: "せいめい",
    month: "4",
    day: "9",
    ko: "鴻雁かえる",
    ko_yomi: "こうがん かえる",
  },
  {
    season: "春",
    sekki: "清明",
    sekki_yomi: "せいめい",
    month: "4",
    day: "14",
    ko: "虹始めてあらわる",
    ko_yomi: "にじ はじめてあらわる",
  },
  {
    season: "春",
    sekki: "穀雨",
    sekki_yomi: "こくう",
    month: "4",
    day: "19",
    ko: "葭始めて生ず",
    ko_yomi: "あし はじめてしょうず",
  },
  {
    season: "春",
    sekki: "穀雨",
    sekki_yomi: "こくう",
    month: "4",
    day: "25",
    ko: "霜止で苗出ずる",
    ko_yomi: "しもやんで なえいずる",
  },
  {
    season: "春",
    sekki: "穀雨",
    sekki_yomi: "こくう",
    month: "4",
    day: "30",
    ko: "牡丹はなさく",
    ko_yomi: "ぼたん はなさく",
  },
  {
    season: "夏",
    sekki: "立夏",
    sekki_yomi: "りっか",
    month: "5",
    day: "5",
    ko: "蛙始めて鳴く",
    ko_yomi: "かわず はじめてなく",
  },
  {
    season: "夏",
    sekki: "立夏",
    sekki_yomi: "りっか",
    month: "5",
    day: "10",
    ko: "みみず出ずる",
    ko_yomi: "みみず いずる",
  },
  {
    season: "夏",
    sekki: "立夏",
    sekki_yomi: "りっか",
    month: "5",
    day: "15",
    ko: "竹のこ生ず",
    ko_yomi: "たけのこ しょうず",
  },
  {
    season: "夏",
    sekki: "小満",
    sekki_yomi: "しょうまん",
    month: "5",
    day: "20",
    ko: "蚕起きて桑を食む",
    ko_yomi: "かいこおきて くわをはむ",
  },
  {
    season: "夏",
    sekki: "小満",
    sekki_yomi: "しょうまん",
    month: "5",
    day: "26",
    ko: "紅花栄う",
    ko_yomi: "べにばな さかう",
  },
  {
    season: "夏",
    sekki: "小満",
    sekki_yomi: "しょうまん",
    month: "5",
    day: "31",
    ko: "麦秋至る",
    ko_yomi: "むぎのとき いたる",
  },
  {
    season: "夏",
    sekki: "芒種",
    sekki_yomi: "ぼうしゅ",
    month: "6",
    day: "5",
    ko: "蟷螂生ず",
    ko_yomi: "かまきり しょうず",
  },
  {
    season: "夏",
    sekki: "芒種",
    sekki_yomi: "ぼうしゅ",
    month: "6",
    day: "10",
    ko: "腐れたる草蛍となる",
    ko_yomi: "くされたるくさ ほたるとなる",
  },
  {
    season: "夏",
    sekki: "芒種",
    sekki_yomi: "ぼうしゅ",
    month: "6",
    day: "16",
    ko: "梅のみ黄ばむ",
    ko_yomi: "うめのみ きばむ",
  },
  {
    season: "夏",
    sekki: "夏至",
    sekki_yomi: "げし",
    month: "6",
    day: "21",
    ko: "乃東枯る",
    ko_yomi: "なつかれくさ かるる",
  },
  {
    season: "夏",
    sekki: "夏至",
    sekki_yomi: "げし",
    month: "6",
    day: "26",
    ko: "菖蒲はなさく",
    ko_yomi: "あやめ はなさく",
  },
  {
    season: "夏",
    sekki: "夏至",
    sekki_yomi: "げし",
    month: "7",
    day: "1",
    ko: "半夏生ず",
    ko_yomi: "はんげ しょうず",
  },
  {
    season: "夏",
    sekki: "小暑",
    sekki_yomi: "しょうしょ",
    month: "7",
    day: "7",
    ko: "温風至る",
    ko_yomi: "あつかぜ いたる",
  },
  {
    season: "夏",
    sekki: "小暑",
    sekki_yomi: "しょうしょ",
    month: "7",
    day: "13",
    ko: "蓮始めて開く",
    ko_yomi: "はす はじめてひらく",
  },
  {
    season: "夏",
    sekki: "小暑",
    sekki_yomi: "しょうしょ",
    month: "7",
    day: "18",
    ko: "鷹乃ちわざをならう",
    ko_yomi: "たかすなわち わざをならう",
  },
  {
    season: "夏",
    sekki: "大暑",
    sekki_yomi: "たいしょ",
    month: "7",
    day: "23",
    ko: "桐始めて花を結ぶ",
    ko_yomi: "きりはじめて はなをむすぶ",
  },
  {
    season: "夏",
    sekki: "大暑",
    sekki_yomi: "たいしょ",
    month: "7",
    day: "28",
    ko: "土潤いてむし暑し",
    ko_yomi: "つちうるおいて むしあつし",
  },
  {
    season: "夏",
    sekki: "大暑",
    sekki_yomi: "たいしょ",
    month: "8",
    day: "2",
    ko: "大雨時々に降る",
    ko_yomi: "たいう ときどきにふる",
  },
  {
    season: "秋",
    sekki: "立秋",
    sekki_yomi: "りっしゅう",
    month: "8",
    day: "8",
    ko: "涼風至る",
    ko_yomi: "すずかぜ いたる",
  },
  {
    season: "秋",
    sekki: "立秋",
    sekki_yomi: "りっしゅう",
    month: "8",
    day: "13",
    ko: "寒蝉鳴く",
    ko_yomi: "ひぐらし なく",
  },
  {
    season: "秋",
    sekki: "立秋",
    sekki_yomi: "りっしゅう",
    month: "8",
    day: "18",
    ko: "深き霧まとう",
    ko_yomi: "ふかききり まとう",
  },
  {
    season: "秋",
    sekki: "処暑",
    sekki_yomi: "しょしょ",
    month: "8",
    day: "23",
    ko: "綿のはなしべ開く",
    ko_yomi: "わたの はなしべひらく",
  },
  {
    season: "秋",
    sekki: "処暑",
    sekki_yomi: "しょしょ",
    month: "8",
    day: "28",
    ko: "天地始めてさむし",
    ko_yomi: "てんち はじめてさむし",
  },
  {
    season: "秋",
    sekki: "処暑",
    sekki_yomi: "しょしょ",
    month: "9",
    day: "3",
    ko: "禾乃ちみのる",
    ko_yomi: "こくもの すなわちみのる",
  },
  {
    season: "秋",
    sekki: "白露",
    sekki_yomi: "はくろ",
    month: "9",
    day: "8",
    ko: "草露白し",
    ko_yomi: "くさつゆ しろし",
  },
  {
    season: "秋",
    sekki: "白露",
    sekki_yomi: "はくろ",
    month: "9",
    day: "13",
    ko: "鶺鴒鳴く",
    ko_yomi: "せきれい なく",
  },
  {
    season: "秋",
    sekki: "白露",
    sekki_yomi: "はくろ",
    month: "9",
    day: "18",
    ko: "玄鳥去る",
    ko_yomi: "つばめ さる",
  },
  {
    season: "秋",
    sekki: "秋分",
    sekki_yomi: "しゅうぶん",
    month: "9",
    day: "23",
    ko: "雷乃ち声を収む",
    ko_yomi: "かみなりすなわち こえをおさむ",
  },
  {
    season: "秋",
    sekki: "秋分",
    sekki_yomi: "しゅうぶん",
    month: "9",
    day: "28",
    ko: "虫かくれて戸をふさぐ",
    ko_yomi: "むしかくれて とをふさぐ",
  },
  {
    season: "秋",
    sekki: "秋分",
    sekki_yomi: "しゅうぶん",
    month: "10",
    day: "3",
    ko: "水始めて涸る",
    ko_yomi: "みず はじめてかるる",
  },
  {
    season: "秋",
    sekki: "寒露",
    sekki_yomi: "かんろ",
    month: "10",
    day: "8",
    ko: "鴻雁来る",
    ko_yomi: "こうがん きたる",
  },
  {
    season: "秋",
    sekki: "寒露",
    sekki_yomi: "かんろ",
    month: "10",
    day: "14",
    ko: "菊花開く",
    ko_yomi: "きくのはな ひらく",
  },
  {
    season: "秋",
    sekki: "寒露",
    sekki_yomi: "かんろ",
    month: "10",
    day: "19",
    ko: "蟋蟀戸にあり",
    ko_yomi: "きりぎりす とにあり",
  },
  {
    season: "秋",
    sekki: "霜降",
    sekki_yomi: "そうこう",
    month: "10",
    day: "24",
    ko: "霜始めて降る",
    ko_yomi: "しも はじめてふる",
  },
  {
    season: "秋",
    sekki: "霜降",
    sekki_yomi: "そうこう",
    month: "10",
    day: "29",
    ko: "小雨ときどきふる",
    ko_yomi: "こさめ ときどきふる",
  },
  {
    season: "秋",
    sekki: "霜降",
    sekki_yomi: "そうこう",
    month: "11",
    day: "3",
    ko: "楓蔦黄ばむ",
    ko_yomi: "もみじつた きばむ",
  },
  {
    season: "冬",
    sekki: "立冬",
    sekki_yomi: "りっとう",
    month: "11",
    day: "8",
    ko: "山茶始めて開く",
    ko_yomi: "つばき はじめてひらく",
  },
  {
    season: "冬",
    sekki: "立冬",
    sekki_yomi: "りっとう",
    month: "11",
    day: "13",
    ko: "地始めて凍る",
    ko_yomi: "ち はじめてこおる",
  },
  {
    season: "冬",
    sekki: "立冬",
    sekki_yomi: "りっとう",
    month: "11",
    day: "18",
    ko: "金盞香",
    ko_yomi: "きんせんか さく",
  },
  {
    season: "冬",
    sekki: "小雪",
    sekki_yomi: "しょうせつ",
    month: "11",
    day: "22",
    ko: "虹かくれて見えず",
    ko_yomi: "にじ かくれてみえず",
  },
  {
    season: "冬",
    sekki: "小雪",
    sekki_yomi: "しょうせつ",
    month: "11",
    day: "27",
    ko: "朔風葉を払う",
    ko_yomi: "きたかぜ このはをはらう",
  },
  {
    season: "冬",
    sekki: "小雪",
    sekki_yomi: "しょうせつ",
    month: "12",
    day: "2",
    ko: "橘始めて黄ばむ",
    ko_yomi: "たちばな はじめてきばむ",
  },
  {
    season: "冬",
    sekki: "大雪",
    sekki_yomi: "たいせつ",
    month: "12",
    day: "7",
    ko: "閉塞冬となる",
    ko_yomi: "そらさむく ふゆとなる",
  },
  {
    season: "冬",
    sekki: "大雪",
    sekki_yomi: "たいせつ",
    month: "12",
    day: "12",
    ko: "熊穴にこもる",
    ko_yomi: "くま あなにこもる",
  },
  {
    season: "冬",
    sekki: "大雪",
    sekki_yomi: "たいせつ",
    month: "12",
    day: "17",
    ko: "さけの魚群がる",
    ko_yomi: "さけのうお むらがる",
  },
  {
    season: "冬",
    sekki: "冬至",
    sekki_yomi: "とうじ",
    month: "12",
    day: "22",
    ko: "乃東生ず",
    ko_yomi: "なつかれくさ しょうず",
  },
  {
    season: "冬",
    sekki: "冬至",
    sekki_yomi: "とうじ",
    month: "12",
    day: "27",
    ko: "さわしかの角おつる",
    ko_yomi: "さわしかのつの おつる",
  },
  {
    season: "冬",
    sekki: "冬至",
    sekki_yomi: "とうじ",
    month: "1",
    day: "1",
    ko: "雪下りて麦のびる",
    ko_yomi: "ゆきわたりて むぎのびる",
  },
  {
    season: "冬",
    sekki: "小寒",
    sekki_yomi: "しょうかん",
    month: "1",
    day: "6",
    ko: "芹乃ち栄う",
    ko_yomi: "せりすなわち さかう",
  },
  {
    season: "冬",
    sekki: "小寒",
    sekki_yomi: "しょうかん",
    month: "1",
    day: "11",
    ko: "泉水温をふくむ",
    ko_yomi: "しみず あたたかをふくむ",
  },
  {
    season: "冬",
    sekki: "小寒",
    sekki_yomi: "しょうかん",
    month: "1",
    day: "16",
    ko: "雉始めてなく",
    ko_yomi: "きじ はじめてなく",
  },
  {
    season: "冬",
    sekki: "大寒",
    sekki_yomi: "だいかん",
    month: "1",
    day: "20",
    ko: "款冬華く",
    ko_yomi: "ふきの はなさく",
  },
  {
    season: "冬",
    sekki: "大寒",
    sekki_yomi: "だいかん",
    month: "1",
    day: "25",
    ko: "水沢氷つめる",
    ko_yomi: "さわみず こおりつめる",
  },
  {
    season: "冬",
    sekki: "大寒",
    sekki_yomi: "だいかん",
    month: "1",
    day: "30",
    ko: "鶏始めてとやにつく",
    ko_yomi: "にわとり はじめてとやにつく",
  },
];

_sekkis.sort(function (a, b) {
  return Number(a.month) < Number(b.month) ? 1 : -1;
});

export const sekkis = _sekkis;
